version: "3.8"

services:
  web:
    image: 704274790393.dkr.ecr.eu-west-1.amazonaws.com/varlens-frontend:latest
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend

  api:
    image: 704274790393.dkr.ecr.eu-west-1.amazonaws.com/varlens-backend:latest
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
     - network-backend
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    networks: 
     - network-backend

networks:
  network-backend:

volumes: 
  mongodb_data:

