- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Install unzip (dependency for AWS CLI)
  apt:
    name: unzip
    state: present
    update_cache: yes

- name: Download AWS CLI v2 installer
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
    mode: '0644'

- name: Unzip AWS CLI installer
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: yes

- name: Install AWS CLI v2
  command: /tmp/aws/install --update
  args:
    creates: /usr/local/bin/aws

- name: Login to AWS ECR
  shell: |
    aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 704274790393.dkr.ecr.eu-west-1.amazonaws.com

- name: Copy docker-compose file
  copy:
    src: docker-compose.yml
    dest: /home/ubuntu/docker-compose.yml
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Start application with Docker Compose
  command: docker-compose up -d
  args:
    chdir: /home/ubuntu
