name: Trivy Image Scan

on:
  push:
    branches: [master] 
  pull_request:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build varlens-frontend image
        run: docker build -t varlens-frontend ./frontend

      - name: Build varlens-backend image
        run: docker build -t varlens-backend ./backend

      - name: Scan varlens-frontend with Trivy
        uses: aquasecurity/trivy-action@v0.12.0
        with:
          scan-type: image
          image-ref: varlens-frontend
          format: table
          severity: CRITICAL,HIGH

      - name: Scan varlens-backend with Trivy
        uses: aquasecurity/trivy-action@v0.12.0
        with:
          scan-type: image
          image-ref: varlens-backend
          format: table
          severity: CRITICAL,HIGH


